%%
% Environmental Parameters
global g rho mass...
    W N_lift N_thrust

% Vehicle aerodynamic characteristics
global k_total CD0_total CLa_total...
    CL0_total CLmax_total A_aero...
    Cl Cd 

% Thruster drag increase model
global LifterDrag Lift Drag

% Energy storage
global batteryCells batteryVoltage batteryCapacity...
    numBatteries UsableEnergyFactor capacity...
    powerCorrection

% Propeller Parameters
global D A_prop CT...
    CQ RPSMax TMax...
    kappa sigma_rotor...
    rotorRPS_fun Ph RPS_h...
    P0_per Cd0_rotor thrusterPower...
    lifterPower
%%