%%
% Environmental Parameters
global g rho mass...
    W N_lift N_thrust

% Vehicle aerodynamic characteristics
global k_total CD0_total CLa_total...
    CL0_total CLmax_total A_aero...
    Cl Cd 

% Thruster drag increase model
global LifterDrag Lift Drag

% Energy storage
global batteryCells batteryVoltage batteryCapacity...
    numBatteries UsableEnergyFactor capacity...
    powerCorrection

% Propeller Parameters
global D_lifter A_prop_lifter CT_lifter...
    CQ_lifter RPSMax_lifter TMax_lifter...
    rotorRPS_fun_lifter Ph_lifter RPS_h_lifter...
    P0_per_lifter Cd0_rotor_lifter...
    D_thruster A_prop_thruster CT_thruster...
    CQ_thruster RPSMax_thruster TMax_thruster...
    rotorRPS_fun_thruster Ph_thruster RPS_h_thruster...
    P0_per_thruster Cd0_rotor_thruster...
    kappa sigma_rotor...
    thrusterPower lifterPower
%%